name: cinemapedia
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  animate_do: ^4.2.0
  card_swiper: ^3.0.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  intl: ^0.20.2

dev_dependencies:
  drift_dev: ^2.28.3
  build_runner: ^2.7.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
